# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{log_buddy}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Sanheim"]
  s.date = %q{2010-12-06}
  s.description = %q{Log statements along with their name easily.  Mixin a logger everywhere when you need it.}
  s.email = %q{rsanheim@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".rvmrc",
    ".treasure_map.rb",
    "CHANGELOG",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "examples.rb",
    "init.rb",
    "lib/log_buddy.rb",
    "lib/log_buddy/mixin.rb",
    "lib/log_buddy/utils.rb",
    "lib/log_buddy/version.rb",
    "log_buddy.gemspec",
    "spec/log_buddy/log_buddy_init_spec.rb",
    "spec/log_buddy/log_buddy_spec.rb",
    "spec/log_buddy/log_spec.rb",
    "spec/log_buddy/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/relevance/log_buddy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Log Buddy is your little development buddy.}
  s.test_files = [
    "spec/log_buddy/log_buddy_init_spec.rb",
    "spec/log_buddy/log_buddy_spec.rb",
    "spec/log_buddy/log_spec.rb",
    "spec/log_buddy/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.2"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<sdoc>, ["~> 0.3"])
      s.add_development_dependency(%q<sdoc-helpers>, ["~> 0.1"])
      s.add_development_dependency(%q<rdiscount>, ["~> 1.6"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.2"])
      s.add_dependency(%q<mocha>, ["~> 0.9"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.2"])
    s.add_dependency(%q<mocha>, ["~> 0.9"])
  end
end

