
# Gem::Specification for Log_buddy-0.0.3
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: log_buddy
version: !ruby/object:Gem::Version 
  version: 0.0.3
platform: ruby
authors: 
- Rob Sanheim - Relevance
autorequire: 
bindir: bin

date: 2008-07-01 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: allison
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: markaby
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Log statements along with their name easily.  Mixin a logger everywhere when you need it.
email: opensource@thinkrelevance.com
executables: 
- log_buddy
extensions: []

extra_rdoc_files: 
- CHANGELOG
- README.rdoc
- bin/log_buddy
- lib/log_buddy.rb
files: 
- CHANGELOG
- Manifest
- README.rdoc
- Rakefile
- bin/log_buddy
- examples.rb
- init.rb
- lib/log_buddy.rb
- test/test_log_buddy.rb
- log_buddy.gemspec
has_rdoc: true
homepage: http://opensource.thinkrelevance.com/wiki/log_buddy
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Log_buddy
- --main
- README.rdoc
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: thinkrelevance
rubygems_version: 1.2.0
specification_version: 2
summary: Log Buddy is your little development buddy.
test_files: 
- test/test_log_buddy.rb
